# Generated by Django 4.2.1 on 2023-06-08 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('incident_pk', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('incident_id', models.CharField(max_length=30)),
                ('incident_details', models.TextField(editable=False)),
                ('priority', models.CharField(choices=[('High', 'HIGH'), ('Medium', 'MEDIUM'), ('Low', 'LOW')], max_length=15)),
                ('status', models.CharField(choices=[('Open', 'OPEN'), ('In progress', 'IN PROGRESS'), ('Closed', 'CLOSED')], max_length=15)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('fk_user_uuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'db_table': 'Incidents',
                'abstract': False,
            },
        ),
    ]
