# Generated by Django 4.2.1 on 2023-06-08 16:53

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('uuid_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fname_user', models.CharField(max_length=200)),
                ('mname_user', models.CharField(blank=True, max_length=200, null=True)),
                ('lname_user', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=500, unique=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('joining_dt_user', models.DateTimeField(default=django.utils.timezone.now)),
                ('deactivation_dt_user', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Custom_User',
                'verbose_name_plural': 'Custom_Users',
                'db_table': 'Custom_Users',
                'abstract': False,
            },
        ),
    ]
